name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a13ba2226136962cdaab045831ada51a017f9ff4e117f19773dcc27a47a029fa"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
