name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53775a293a3a52cc93e759b1216ac1aea2f6a10d2cd39d46964d2207e4caa154"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
