name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ccd6739999b72ff6ceba3a1961c4ecc1c9a3ae9c45b25cd0a176d321af0298d"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
