name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0104db767d971c24658efa3339a38db0a199ac7fd4df5360e89304a9fc8fdf7"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
