name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8016fd0cf0f4b53b29eb98b01f8377cecf8054ac7d98e8215e26300b4b9cdaa3"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
