name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83393f739293c623649097b4b7526653bdcfea6ce13271cad94055db17e4b019"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
