name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59f47111b4d9f2e273433dadbb68882316753ca26b0b66c391da15c85ee82ad3"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
