name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "013f16b0b920a6e80f1b7117c593396d0afae3f49a7b920fa9cba3425c186e90"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
