name = "Banana's Better Vanilla Experience"
author = "Imabanana80"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7299b1853ae96744f6fcc6e67cf19009ebc383da008da645bffa019c9a6fb08a"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
